### ISSUE TITLE
slirp4netns sync pipe EOF on Fedora Silverblue 30

### ISSUE THREAD

**Issue by fansari** [debarshiray/toolbox#125]
I have tried to create a toolbox for Fedora 30 but this fails.

```
[fansari@bat ~]$ toolbox -v create --candidate-registry
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: customized user-specific image is fedora-toolbox-fansari:30
toolbox: container is fedora-toolbox-fansari-30
toolbox: checking  value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: parsing value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: checking if image fedora-toolbox-fansari:30 already exists
Error: error getting image "fedora-toolbox-fansari:30": unable to find a name and tag match for fedora-toolbox-fansari in repotags: no such image
toolbox: looking for image localhost/fedora-toolbox:30
Pulling docker://localhost/fedora-toolbox:30
ERRO[0000] exit status 1                                
toolbox: looking for image candidate-registry.fedoraproject.org/f30/fedora-toolbox:30
Pulling docker://candidate-registry.fedoraproject.org/f30/fedora-toolbox:30
Getting image source signatures
Copying blob 934966bfd3bd: 39.95 MiB / 89.22 MiB [============>----------------]
Copying blob 934966bfd3bd: 88.35 MiB / 89.22 MiB [=============================]
Copying blob 934966bfd3bd: 89.22 MiB / 89.22 MiB [=========================] 42s
Copying blob cd73137bf7d1: 56.25 MiB / 56.25 MiB [=========================] 42s
Copying config dbfb7129d38b: 2.75 KiB / 2.75 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
toolbox: base image fedora-toolbox:30 resolved to candidate-registry.fedoraproject.org/f30/fedora-toolbox:30
toolbox: trying to create working container toolbox-working-container-5b0353e2-6395-11e9-b8b5-1c1b0d6163d2
toolbox: trying to configure working container toolbox-working-container-5b0353e2-6395-11e9-b8b5-1c1b0d6163d2
error running container: failed to read from slirp4netns sync pipe: EOF
error while running runtime: exit status 1
ERRO[0000] exit status 1                                
toolbox: failed to make /home a symlink
ERRO[0000] exit status 1               
```

**Comment by debarshiray** [comment]
Looks like `buildah run` failed:
```
toolbox: trying to configure working container toolbox-working-container-5b0353e2-6395-11e9-b8b5-1c1b0d6163d2
error running container: failed to read from slirp4netns sync pipe: EOF
error while running runtime: exit status 1
ERRO[0000] exit status 1                                
toolbox: failed to make /home a symlink
```

Are you still having this problem? What version of buildah do you have  (`rpm -q buildah`)?

**Comment by fansari** [comment]
I have version buildah-1.7-17.dev.git146a0fc.fc30.x86_64.

Today I ran "rpm-ostree upgrade" and tried again. Same version. Same error.

**Comment by debarshiray** [comment]
> I have version buildah-1.7-17.dev.git146a0fc.fc30.x86_64.
> 
> Today I ran "rpm-ostree upgrade" and tried again. Same version. Same error.

Could you try [buildah-1.7-3.git873f001.fc30](https://koji.fedoraproject.org/koji/buildinfo?buildID=1237768)? It's a newer build, but due to a packaging mistake, it's version number isn't considered newer than the one you have by RPM.

You will have to use `rpm-ostree override replace` to replace the package in your Silverblue image.

**Comment by fansari** [comment]
[fansari@bat ~]$ rpm -q buildah
buildah-1.7-3.git873f001.fc30.x86_64

[fansari@bat ~]$ toolbox -v create --candidate-registry
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: customized user-specific image is fedora-toolbox-fansari:30
toolbox: container is fedora-toolbox-fansari-30
toolbox: checking value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: parsing value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: checking if image fedora-toolbox-fansari:30 already exists
Error: error getting image "fedora-toolbox-fansari:30": unable to find a name and tag match for fedora-toolbox-fansari in repotags: no such image
toolbox: looking for image localhost/fedora-toolbox:30
ERRO[0000] exit status 1                                
toolbox: looking for image candidate-registry.fedoraproject.org/f30/fedora-toolbox:30
toolbox: base image fedora-toolbox:30 resolved to candidate-registry.fedoraproject.org/f30/fedora-toolbox:30
toolbox: trying to create working container toolbox-working-container-1b692990-6783-11e9-a99d-1c1b0d6163d2
toolbox: trying to configure working container toolbox-working-container-1b692990-6783-11e9-a99d-1c1b0d6163d2
error running container: failed to read from slirp4netns sync pipe: EOF
error while running runtime: exit status 1
ERRO[0000] exit status 1                                
toolbox: failed to make /home a symlink
ERRO[0000] exit status 1

**Comment by debarshiray** [comment]
Ok, thanks for trying it out @fansari  - the error is the same. :/

**Comment by debarshiray** [comment]
This is https://github.com/containers/buildah/issues/1554

**Comment by fansari** [comment]
One hint: I don't have this error when trying to build the box as root. Anyway - there is another issue then.

```
[root@bat ~]# toolbox -v create --candidate-registry
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: customized user-specific image is fedora-toolbox-root:30
toolbox: container is fedora-toolbox-root-30
toolbox: checking value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: parsing value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: checking if image fedora-toolbox-root:30 already exists
Error: error getting image "fedora-toolbox-root:30": unable to find a name and tag match for fedora-toolbox-root in repotags: no such image
toolbox: looking for image localhost/fedora-toolbox:30
toolbox: looking for image candidate-registry.fedoraproject.org/f30/fedora-toolbox:30
Getting image source signatures
Copying blob 934966bfd3bd [======================================] 89.2MiB / 89.2MiB
Copying blob cd73137bf7d1 [======================================] 56.3MiB / 56.3MiB
Copying config dbfb7129d3 [======================================] 2.8KiB / 2.8KiB
Writing manifest to image destination
Storing signatures
toolbox: base image fedora-toolbox:30 resolved to candidate-registry.fedoraproject.org/f30/fedora-toolbox:30
toolbox: trying to create working container toolbox-working-container-8b667f3e-68f7-11e9-a91b-1c1b0d6163d2
toolbox: trying to configure working container toolbox-working-container-8b667f3e-68f7-11e9-a91b-1c1b0d6163d2
useradd: user 'root' already exists
toolbox: failed to create user root with UID 0
```

```
[root@bat ~]# podman run -it dbfb7129d38b /bin/bash
[root@535c7c958ab5 /]# ls
ls: cannot open directory '.': Permission denied
```

**Comment by debarshiray** [comment]
Yeah, the `toolbox` command isn't really intended to be used as root on the host. We could fix some of the things to make it work, but it's definitely not the primary use-case.

Also, rootless `podman` and rootful `podman` often follow different code paths.

**Comment by debarshiray** [comment]
Closing in favour of https://github.com/containers/buildah/issues/1554
