### ISSUE TITLE
Ask for confirmation before doing downloads

### ISSUE THREAD

**Issue by allanday** [debarshiray/toolbox#134]
If I run `toolbox create`, toolbox immediately starts downloading a rather large image file. This is undesirable for two reasons:

 1. It is bad behaviour to do large downloads without asking first - it could eat someone's data cap, or interfere with other network activity
 2. It's surprising: to the uninitiated, there's nothing about `toolbox create` that suggests that a download will be involved

The simple way to fix this would be to ask for permission before doing the download, like:
```
A toolbox container image is required. Download now? (400MB) [y/N]
```

**Comment by allanday** [comment]
Or you could do two lines:

```
Image required to create toolbox container.
Download fedora-bla-bla-bla-30 (400 MB) ? [y/N]
```

**Comment by debarshiray** [comment]
Yes, I agree. One problem is that there's no easy way to get the size of the impending download. :(

We could hard code the size of the `fedora-toolbox` images until we figure out a better way to get the numbers. Those are the things that most people are going to download, and the figure doesn't need to be very accurate.

**Comment by allanday** [comment]
> Those are the things that most people are going to download, and the figure doesn't need to be very accurate.

Yes, showing an approximate figure would be fine for now.
