### ISSUE TITLE
flatpak-xdg-utils xdg-open does not work in Toolbox

### ISSUE THREAD

**Issue by juhp** [debarshiray/toolbox#147]
IWBNI `xdg-open` etc would work inside toolboxes so one could open URLs etc easily from application running under Toolbox.

Currently:

```
$ xdg-open http://silverblue.fedoraproject.org &
[3] 32529
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open /proc/32529/root
```

**Comment by juhp** [comment]
For now I am working around this with:

```
$ cat > ~/bin/xdg-open << EOF
#!/bin/sh
${TOOLBOX_CONTAINER:+flatpak-spawn --host} /usr/bin/xdg-open $*
EOF
$ chmod u+x ~/bin/xdg-open
```

**Comment by juhp** [comment]
(With toolbox-0.0.10, I replaced `TOOLBOX_CONTAINER` with `TOOLBOX_PATH`.)

**Comment by juhp** [comment]
@vinzent `flatpak-xdg-utils` should probably conflict with `xdg-utils`...

**Comment by debarshiray** [comment]
We should split `flatpak-spawn` into a separate sub-package from the `flatpak-xdg-utils` RPM, and only install that in the `fedora-toolbox` images.

We did something [similar](https://src.fedoraproject.org/rpms/flatpak/c/5da8672e306f87939a8303cca3b619bb8fab435d) for the `flatpak-session-helper` binary recently.

**Comment by debarshiray** [comment]
> IWBNI `xdg-open` etc would work inside toolboxes so one could open
> URLs etc easily from application running under Toolbox.
> 
> Currently:
> 
> ```
> $ xdg-open http://silverblue.fedoraproject.org &
> [3] 32529
> Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open /proc/32529/root
> ```

For the record, I think this is the same problem that https://github.com/flatpak/xdg-desktop-portal/pull/348 was trying to solve.

**Comment by debarshiray** [comment]
The split `flatpak-spawn` builds are now in the repositories, and I have updated our Dockerfiles accordingly. All that's left is to update the OCI images now.

**Comment by debarshiray** [comment]
There's https://github.com/containers/toolbox/issues/291 about the xdg-utils implementation of `xdg-email` and `xdg-open` not working within Toolbx containers, when the application doesn't exist within the container but exists on the host.
