### ISSUE TITLE
PackageKit-command-not-found installs on host

### ISSUE THREAD

**Issue by rlac** [debarshiray/toolbox#158]
OS: Fedora 30 Workstation
toolbox: 0.0.9

Package installation initiated by PackageKit-command-not-found is performed on the host, not in the container.

```
[robc@toolbox ~]$ tig
zsh: tig: command not found...
Install package 'tig' to provide command 'tig'? [N/y] y


 * Waiting in queue... 
 * Loading list of packages.... 
The following packages have to be installed:
 tig-2.4.1-2.fc30.x86_64	Text-mode interface for the git revision control system
Proceed with changes? [N/y] y


 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
Failed to launch: 'tig ': Failed to execute child process “tig” (No such file or directory)

[robc@toolbox ~]$ tig
zsh: tig: command not found...
Install package 'tig' to provide command 'tig'? [N/y] y


 * Waiting in queue... 
 * Loading list of packages.... Failed to install packages: tig-2.4.1-2.fc30.x86_64 is already installed

🔹[robc@toolbox ~]$
```

**Comment by juhp** [comment]
I would rather we remove `PackageKit-command-not-found`, at least until it works..

**Comment by debarshiray** [comment]
> I would rather we remove PackageKit-command-not-found, at least until it works..

I agree. @juhp do you want to take care of updating the images? I will be going on vacation for a week starting tomorrow, so I might not be able to get to it before that.

We haven't respun the `fedora-toolbox` in a while. This is as good a reason as any to do that. :)

**Comment by juhp** [comment]
Sure I can :+1:

**Comment by debarshiray** [comment]
Thanks @juhp
