### ISSUE TITLE
Feature Request - User specified Guests

### ISSUE THREAD

**Issue by kurobeats** [debarshiray/toolbox#173]
Please correct me if I've overlooked an exist feature to achieve this, but I'll be keen to use toolbox to create say an Ubuntu container using, for example, https://hub.docker.com/_/ubuntu/

**Comment by tpopela** [comment]
It should work. Please try to run `toolbox create --image docker.io/library/ubuntu:latest`.

**Comment by znmeb** [comment]
You can sort of do it by specifying an image, say, for exampe, `docker.io/library/ubuntu:bionic`. But it throws some errors if, for example, there's no `root` in `etc/passwd`. And it looks for the "wheel" group, which on Ubuntu is the "sudo" group. I forked the repo to try and fix those minor glitches but if @debarshiray wants to take this on, I think it's worth doing.

That said, the "magic" of toolbox is

a) podman hosting
b) all the mounting that makes it look like you inside the container.

Just factoring that piece out would be all I'd need; I can do the rest with a Dockerfile.

**Comment by debarshiray** [comment]
> It throws some errors if, for example, there's no `root` in `etc/passwd`. And it
> looks for the "wheel" group, which on Ubuntu is the "sudo" group. I forked the
> repo to try and fix those minor glitches but if @debarshiray wants to take this
> on, I think it's worth doing.

@andrunko already fixed the issue with the `wheel` and `sudo` groups in PR #167 and it's part of the 0.0.10 release.

The Ubuntu images do have `root` in `/etc/passwd`, though.

> That said, the "magic" of toolbox is
> 
> a) podman hosting
> b) all the mounting that makes it look like you inside the container.
> 
> Just factoring that piece out would be all I'd need; I can do the rest with a Dockerfile.

Pull requests welcome for other glitches affecting Ubuntu images.

**Comment by debarshiray** [comment]
Please open specific issues or pull requests if you encounter further issues.

I am closing this because it's too generic and you can override the default image to create different kinds of toolbox containers.
