### ISSUE TITLE
/home is not symlinked in container on Silverblue systems

### ISSUE THREAD

**Issue by cjao** [debarshiray/toolbox#185]
According to commit 66e982af, /home should be symlinked to /var/home in the toolbox container on Fedora Silverblue hosts. However, this does not seem to be the case with the latest toolbox 0.0.10.1 on SB 30. I suspect the culprit is commit 8b84b5e, which (among other things) which moved the logic introduced in 66e982af to init_container(). As that function is only executed within the container, it cannot detect whether /home on the host is symlinked to /var/home.

**Comment by debarshiray** [comment]
Oops, good catch!

We need to check for the symbolic link on the host in `create()` and pass that down to the `toolbox init-container` command using a command line flag. Want to submit a pull request for this?

**Comment by cjao** [comment]
See #189.
