### ISSUE TITLE
PS1 line wrapping on long input

### ISSUE THREAD

**Issue by LingCalvin** [debarshiray/toolbox#190]
In the terminal, long text wraps back onto itself.

![wrapping](https://user-images.githubusercontent.com/42983654/59142231-b367e980-8988-11e9-9878-b9fb98ad84fb.png)

I believe this line might be the issue.

https://github.com/debarshiray/toolbox/blob/0886fb466e7a73e7382255cf80c9459ffb1d84ac/profile.d/toolbox.sh#L28

The color sequences should probably be enclosed in `\[\]`.

**Comment by basvdlei** [comment]
Yes, for bash to properly calculate the prompt length, the non printable characters in `PS1` should be enclosed with `\[\]`:
```sh
PS1=$(printf "\[\033[35m\]⬢\[\033[0m\]%s" "[\u@\h \W]\\$ ") 
```

From the bash [manual](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Controlling-the-Prompt):
> \\[     begin a sequence of non-printing characters, which could be used to embed a terminal control sequence into the prompt
> \\]     end a sequence of non-printing characters

Related StackExchange QA: https://unix.stackexchange.com/questions/105958/terminal-prompt-not-wrapping-correctly

**Comment by debarshiray** [comment]
Aha, nice catch! I was wondering what's going on there, but never got around to digging into it. Do you want to file a pull request?

Thanks for stopping by and tracking this down!
