### ISSUE TITLE
Latest toolbox on F30

### ISSUE THREAD

**Issue by alcir** [debarshiray/toolbox#203]
There is 0.0.11-1.fc30 version on updates repository.
This version is not on bodhi.
BTW, updating from 0.0.10-1.fc30 to 0.0.11-1.fc30, I'm no more able to enter in my container:
`toolbox: failed to call org.freedesktop.Flatpak.SessionHelper.RequestSession`

Downgrading the RPM to 0.0.10-1.fc30, the container works as before.

**Comment by davidlt** [comment]
It's available in Bodhi in combined update: https://bodhi.fedoraproject.org/updates/FEDORA-2019-5aca07c69c

**Comment by alcir** [comment]
> It's available in Bodhi in combined update: https://bodhi.fedoraproject.org/updates/FEDORA-2019-5aca07c69c

Uh. Thank you.

BTW upgrading to this version I get the message:  `toolbox: failed to call org.freedesktop.Flatpak.SessionHelper.RequestSession` and I'm unable to create new containers or enter old ones.

**Comment by davidlt** [comment]
You should mention that on Bodhi update instead.

**Comment by alcir** [comment]
Thanks

**Comment by debarshiray** [comment]
> BTW, updating from 0.0.10-1.fc30 to 0.0.11-1.fc30, I'm no more able to enter in my container:
> `toolbox: failed to call org.freedesktop.Flatpak.SessionHelper.RequestSession`

It's because of commit 8db414ddc2d73719c628ca56f345556281e33ebf.

The Fedora `toolbox` package is missing a run-time dependency. Install the `flatpak` RPM to get past it, until it gets sorted out.

**Comment by alcir** [comment]
Installing `flatpak`, now toolbox works.
Thanks.
