### ISSUE TITLE
fedora-toolbox:30 is using rawhide repositories

### ISSUE THREAD

**Issue by Zlopez** [debarshiray/toolbox#204]
I have toolbox running on Fedora Silverblue 30.

Here is the output of `podman ps -a`:
```
CONTAINER ID  IMAGE                                             COMMAND               CREATED      STATUS            PORTS  NAMES
ada65fbbf1a7  registry.fedoraproject.org/f30/fedora-toolbox:30  toolbox --verbose...  13 days ago  Up 9 minutes ago         fedora-toolbox-30
```

And here is the output of `dnf repolist` inside toolbox:
```
repo id                                                                              repo name                                                                                                                                          status
*rawhide                                                                             Fedora - Rawhide - Developmental packages for the next Fedora release                                                                              59,398
*rawhide-modular                                                                     Fedora - Modular Rawhide - Developmental packages for the next Fedora release                                                                          91
```

It should use Fedora 30 repositories, because rawhide ones failing on GPG checks.

**Comment by debarshiray** [comment]
Interesting. I think we did re-spin the images after Fedora 30 was released. Could it be that you have an old image in your local cache?

Either way, it can't hurt to update the images again.

**Comment by Zlopez** [comment]
I removed the current pod and did `toolbox create` again. It downloaded F30 image again.

But you are right, I have 9 months old image, when I list them with `podman images`, I forgot about this one.

Interesting question: How this will be handled in the future, when new Fedora will be released? Would you need to create a new toolbox?

**Comment by juhp** [comment]
The toolbox container version defaults to the installed release (under Fedora) - though nothing to stop you from upgrading your toolbox container to the next release when you want with say: `dnf upgrade --releasever=31`, though personally I would suggest to "reprovision". It might be good to have a small tool to list the additional packages that had been added to one's own toolbox.

**Comment by juhp** [comment]
Also does toolbox try to pull before creating a toolbox?

**Comment by debarshiray** [comment]
The `fedora-toolbox` images were recently updated by @juhp
