### ISSUE TITLE
toolbox gives coredump messages first time but works next time

### ISSUE THREAD

**Issue by pnemade** [debarshiray/toolbox#220]
I am using Fedora Silverblue 30 and have podman-1.4.4-1.fc30. Everytime I freshly start my system and uses `toolbox enter` I get below messages

```
/usr/bin/toolbox: line 1126: 13733 Aborted (core dumped) $prefix_sudo podman container exists "$toolbox_container_old_v1" 2>&3
/usr/bin/toolbox: line 1126: 13757 Aborted (core dumped) $prefix_sudo podman container exists "$toolbox_container_old_v2" 2>&3 
toolbox: container fedora-toolbox-30 not found 
Entering container fedora-toolbox-30 instead. 
Use the 'create' command to create a different toolbox. 
Try 'toolbox --help' for more information.
```

But then If I attempt to start toolbox again, it does not give any message and enter works fine.

**Comment by juhp** [comment]
The podman crash was reported in containers/libpod#3520.
Then if more than 2 toolbox containers exist, toolbox fails to start the first time.
(If there is only one toolbox, the toolbox still starts despite those podman crashes.)

**Comment by debarshiray** [comment]
Thank you very much for testing it out and reporting this. Let's track this on the Podman issue tracker.
