### ISSUE TITLE
Network debugging cannot be performed inside the toolbox

### ISSUE THREAD

**Issue by mildred** [debarshiray/toolbox#225]
network debugging cannot happen inside the toolbox for lack of root privileges.

Running tools such as tcpdump, traceroute, and the like must be done on the host. Ideally, we should find some way to be able to access the host root user from within the toolbox (using the host user password of course)

**Comment by debarshiray** [comment]
Umm... are you sure about this? `traceroute gnu.org` worked for me inside a freshly created toolbox container. Could it be that you have an old container which might have looked different from newer ones?

Random observation: I see that Silverblue 30 doesn't come with `traceroute`, but has `tracepath` instead.

**Comment by mildred** [comment]
You're right, traceroute works. But ping does not (ping: socket: 
Operation not permitted) and nmap cannot use root-only algorithms (mnap 
--privileged). That's not necessarily an issue with the toolbox as it 
may not be its goal to address this, but this is something that's 
missing when working with Silverblue in general.

**Comment by debarshiray** [comment]
For `nmap` there's https://github.com/debarshiray/toolbox/issues/67, and for `ping` there's https://github.com/debarshiray/toolbox/issues/214

Let's continue in those narrower issues. :)
