### ISSUE TITLE
Are there any alternatives to toolbox? (i.e. other implementations)

### ISSUE THREAD

**Issue by eriksjolund** [debarshiray/toolbox#227]
To understand some software it is also good to know about the alternatives.

What other implementations are there of software doing similar things as this GitHub project?

**Comment by j1mc** [comment]
Colin Walters has a Toolbox implementation written in Rust: https://github.com/cgwalters/coretoolbox

**Comment by j1mc** [comment]
This ticket can be closed --- it's not an issue, it's a support question.
