### ISSUE TITLE
toolbox seems to not clean up lock files properly

### ISSUE THREAD

**Issue by flo-l** [debarshiray/toolbox#228]
I rebooted my fedora silverblue box with some toolbox sessions still running. I couldn't enter the running containers anymore after the reboot.

Here is the error message:

```
$ toolbox -v enter -c CONTAINER_NAME
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user USER
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.4.4 is unchanged
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is CONTAINER_NAME
toolbox: checking if container CONTAINER_NAME exists
ERRO[0000] Error refreshing container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: error acquiring lock 0 for container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: file exists 
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: trying to start container CONTAINER_NAME
Error: unable to start container "CONTAINER_NAME": error reading container (probably exited) json message: EOF
toolbox: failed to start container CONTAINER_NAME
```

I'm no expert but this seems to be a problem with lock file cleanup.

Anyhow I need this container running for work, so if anybody knows where this lock file is on my disk so I can delete it I'd be very happy :)

If you need more information feel free to reach out to me via this issue.

**Comment by debarshiray** [comment]
This is from Podman:
```
ERRO[0000] Error refreshing container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: error acquiring lock 0 for container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: file exists 
```

I vaguely recall seeing this before but cannot recall any references.

**Comment by debarshiray** [comment]
A few things to try:

Does this work:
```
$ podman container exists CONTAINER_NAME
```

What about this:
```
$ podman start CONTAINER_NAME
```

**Comment by flo-l** [comment]
thank you for the fast response!

the first one succeeds without printing anything (ret status 0) and the second one gives me:

    Error: unable to start container "CONTAINER_NAME": error reading container (probably exited) json message: EOF

**Comment by debarshiray** [comment]
Ok. It might be that the container's entry point is failing.

What do you get from these:
```
$ podman inspect --type container --format "{{.Args}}" CONTAINER_NAME
...
$ podman start --attach CONTAINER_NAME
...
```

**Comment by flo-l** [comment]
1st: `ERRO[0000] Error refreshing container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: error acquiring lock 0 for container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: file exists 
[+Inf]
`

2nd: `Error: unable to start container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: error reading container (probably exited) json message: EOF
`

**Comment by mheon** [comment]
`podman system renumber` ought to fix this

**Comment by flo-l** [comment]
@mheon this just broke all my containers.

```
podman system renumber
ERRO[0000] Error refreshing container 0701f065b7af16c4829290d4fbd9afe1152d38654e2a23d6cf908f85faab1989: error acquiring lock 0 for container 0701f065b7af16c4829290d4fbd9afe1152d38654e2a23d6cf908f85faab1989: file exists 
ERRO[0000] Error refreshing container 6ccd3d10bcfcab939b1cceed530f799e65731d9f92d07c1f643afd0e4eca9893: error acquiring lock 1 for container 6ccd3d10bcfcab939b1cceed530f799e65731d9f92d07c1f643afd0e4eca9893: file exists 
ERRO[0000] Error refreshing container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: error acquiring lock 2 for container 7ca874bde0aa9bde50f5ce6dd606f1ff7f8ccbaa05e8e40d02aba77499dc8399: file exists 

```

**Comment by flo-l** [comment]
subsequent calls to `podman system renumber` don't produce any output and terminate with an exit status of 0. My containers are still broken.

**Comment by mheon** [comment]
Broken how? If renumber is returning 0, that issue with refresh should be
gone. What errors are you seeing?

**Comment by flo-l** [comment]
I got `Error: unable to start container`.

But I checked just now, several reboots later, and all my containers work like a charm. So renumbering worked in the end. Thank you very much for your help.

**Comment by debarshiray** [comment]
> But I checked just now, several reboots later, and all my containers work
> like a charm. So renumbering worked in the end. Thank you very much
> for your help.

I am very happy to hear that! :) Thanks for helping out, @mheon
