### ISSUE TITLE
Add fedpkg to the image

### ISSUE THREAD

**Issue by thmo** [debarshiray/toolbox#232]
SSIA: It would be nice to have the `fedpkg` tool available in the image.

**Comment by debarshiray** [comment]
We aim to replicate a similar command line user experience as the default Silverblue or Workstation installation with the `fedora-toolbox` images. Note that the images also don't have things like GCC.

I'd suggest using a Dockerfile to layer `fedpkg` on top of the `fedora-toolbox` images if you don't want to repeatedly `dnf install` it.
