### ISSUE TITLE
Allow running toolboxes not matching the host OS

### ISSUE THREAD

**Issue by ibotty** [debarshiray/toolbox#234]
It would be great to be able to run toolboxes with a different base OS, e.g. debian.

**Comment by debarshiray** [comment]
This already works as long as someone takes care of the little itty-bitty integration details. eg., @andrunko maintains Toolbox for EndlessOS which is a Debian derivative.

We are already aware of a [problem](https://github.com/debarshiray/toolbox/issues/187) that affects `systemd-resolvd` systems.
