### ISSUE TITLE
Kerberos does not work in toolbox containers

### ISSUE THREAD

**Issue by martinpitt** [debarshiray/toolbox#235]
It's no surprise that just the default Fedora kerberos config does not work in containers, as the kernel keyring is not namespace aware.

toolbox seems to be aware of that, as it writes a special config file:
```
$ cat /etc/krb5.conf.d/kcm_default_ccache 
# Written by Toolbox
# https://github.com/debarshiray/toolbox
#
# # To disable the KCM credential cache, comment out the following lines.

[libdefaults]
    default_ccache_name = KCM:
```

Which overrides /etc/krb5.conf's default configuration of `default_ccache_name = KEYRING:persistent:%{uid}`. ([KCM docs](http://web.mit.edu/kerberos/www/krb5-1.16/doc/basic/ccache_def.html))

However, this still does not work by default:
```
$ klist
klist: No KCM server found while resolving ccache

$ kinit user@REALM.COM
kinit: No KCM server found while getting default ccache
```
I finally found https://fedoraproject.org/wiki/Changes/KerberosKCMCache (which is not quite obvious!) and installed `sssd-krb5`, but I still get the same error. Apparently this is just an sssd plugin, but that's a system service and thus does not run in toolbox.

The only way how I got it working was to override the configuration:
```
$ cat /etc/krb5.conf.d/0_file_ccache
[libdefaults]
    default_ccache_name = FILE:/tmp/krb5.ccache
```

Is there a way to make this work out of the box? Adding a pointer to documentation to /etc/krb5.conf.d/kcm_default_ccache would already be helpful.

Thanks!

**Comment by debarshiray** [comment]
Hey @martinpitt , good question. :)

On recent versions of legacy Workstation and Silverblue that use KCM caches, it should already be working out of the box. Toolbox containers created with recent versions of Toolbox should have `/run/..heim_org.h5l.kcm-socket` bind mounted inside the container. That's the socket over which `krb5` clients talk to the KCM server. There's some hacky code for that in `/usr/bin/toolbox` - look for `systemctl`.

I believe that the RPM that you need is `sssd-kcm`, not `sssd-krb5`.

**Comment by martinpitt** [comment]
Ah, of course I meant sssd-kcm, sorry. Oh, so this needs to run on the *host*, I see! I have a custom OSTree where this isn't included. I'll try that, and report back if it still does not work. Thank you!

**Comment by debarshiray** [comment]
I am glad it worked out for you. :)

**Comment by mambelli** [comment]
I have krb5-workstation 1.21.1-4.el9_5. and it did not work out of the box
I used @martinpitt suggestion above and I had to modify the file name to allow it to work for multiple users in the container (I used parameter expansion):
```
$ cat /etc/krb5.conf.d/0_file_ccache
[libdefaults]
    default_ccache_name = FILE:/tmp/krb5.%{uid}.ccache
```
