### ISSUE TITLE
Limited size of terminal window in toolbox

### ISSUE THREAD

**Issue by mvala** [debarshiray/toolbox#263]
Usually, i am running in maximized terminal window. Recently, i found out that size of visible window in toolbox is limited. Here is example when running `mc`
![Screenshot from 2019-09-17 07-43-07](https://user-images.githubusercontent.com/65018/65017488-d0fd0580-d91e-11e9-96f1-d24f349ecd52.png)
 
Before it was working fine. Can you give me hint how to fix it?

**Comment by tpopela** [comment]
Looks like it was a regression in podman - https://github.com/debarshiray/toolbox/pull/243.

**Comment by debarshiray** [comment]
Yes it was a regression in the Podman 1.5.x series.

**Comment by debarshiray** [comment]
/duplicate of https://github.com/debarshiray/toolbox/issues/242
