### ISSUE TITLE
$HOME is not set when using crun as the OCI runtime

### ISSUE THREAD

**Issue by fmuellner** [debarshiray/toolbox#266]
On F31 silverblue, the HOME env variable is unset in toolbox containers.

I suspect the issue is somewhere down the stack - toolbox' `init-container` seems to work, at least the home directory appears correctly in the container's `/etc/passwd` - but I don't know how podman/libpod/crun play together, so filing against the entry point.

**Comment by debarshiray** [comment]
Yeah, @returntrip noticed this same problem yesterday.

Could you check a few things? eg., `podman run`.
```
$ podman run --env TERM=$TERM --rm -it registry.fedoraproject.org/f31/fedora-toolbox:31 /bin/bash
```

Then `podman exec`:
```
$ podman create --name foo registry.fedoraproject.org/f31/fedora-toolbox:31 sleep +Inf
$ podman start foo
$ podman exec --env TERM=$TERM -it foo /bin/bash
```

Is $HOME set inside the shell in both those cases?

**Comment by debarshiray** [comment]
It's probably `crun` related, because I tried the newer Podman builds on Fedora 30 and 29, which use `runc`, and they were fine.

**Comment by returntrip** [comment]
@debarshiray 

```
$ podman run --env TERM=$TERM --rm -it registry.fedoraproject.org/f31/fedora-toolbox:31 /bin/bash
[root@5e5b539cc057 /]# echo $HOME
<blank>
```

and

```
podman exec --env TERM=$TERM -it foo /bin/bash
[root@2fdca7bc6092 /]# echo $HOME
<blank>
```

**Comment by bilelmoussaoui** [comment]
I'm getting this when I try to start a container on Fedora Silverblue 31
<pre>
[bilelmussaoui@localhost ~]$ podman start foo
Error: unable to start container "foo": time="2019-09-21T02:34:04+02:00" level=warning msg="signal: killed"
time="2019-09-21T02:34:04+02:00" level=error msg="container_linux.go:346: starting container process caused \"process_linux.go:297: applying cgroup configuration for process caused \\\"mountpoint for cgroup not found\\\"\"\n"
container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"mountpoint for cgroup not found\"": OCI runtime error
</pre>

**Comment by debarshiray** [comment]
@bilelmoussaoui that's a different issue. It sounds like you are using [runc with Cgroups v2](https://github.com/debarshiray/toolbox/issues/246). If that's not the case, then it would be better to open a separate issue.

**Comment by rhatdan** [comment]
Does https://github.com/containers/libpod/pull/4068 fix this?

**Comment by juhp** [comment]
It works for me:

```
$ rpm -q podman
podman-1.6.0-0.12.dev.git819b63c.fc32.x86_64
$ podman run --rm fedora printenv HOME
/root
```

**Comment by returntrip** [comment]
I have tested `podman-1.6.0-0.18.dev.git6ce8d05.fc32.x86_64` on Silverblue 31 and `HOME` is now set correctly:

```
⬢[returntrip@toolbox returntrip]$ uname -a
Linux toolbox 5.3.0-1.fc31.x86_64 #1 SMP Mon Sep 16 12:34:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
⬢[returntrip@toolbox returntrip]$ echo $HOME
/home/returntrip
```

Guessing this [commit](https://github.com/containers/libpod/commit/f5951c7305306967a89de09d957ccd5699ec3f85) fixed the issue.

**Comment by juhp** [comment]
Yes, see containers/libpod#4074

**Comment by debarshiray** [comment]
Ok, let's consider this fixed then.
