### ISSUE TITLE
Bridging the gap between Flatpaks and Toolbox?

### ISSUE THREAD

**Issue by rosskarchner** [debarshiray/toolbox#51]
I've been working on a Groovy project, in my toolbox environment (which is fantastic, thank you for building this!), and got the crazy idea to try IntelliJ. I did the obvious thing, and installed the IntelliJ flatpak.

It turns out that IntelliJ wants to know where your JRE is, and I was stuck because the JRE I was using lives in the toolbox container.

I could easily imagine a bunch of other variations where someone might want a flatpak-managed IDE to execute code in the toolbox container. Say, Visual Studio Code or Atom or gvim, with python, ruby, or node.js running in the toolbox container.

Is there, today, a recommended way of dealing with this?

If not, is there anything planned?

**Comment by debarshiray** [comment]
There isn't a recommended way of doing this, yet; but @owtaylor is working on something. He has something brewing here: https://github.com/owtaylor/fedora-toolbox/tree/toolboxd

**Comment by rosskarchner** [comment]
that looks pretty cool!

**Comment by abiosoft** [comment]
Is there a way to access the root filesystem of the container(s) on the host? That may provide a way out.

**Comment by abiosoft** [comment]
Found a trick that sorta works for me. I simply create a symbolic link for `/usr` directory within $HOME. And I was able to access programs living in the container.

**Comment by ibotty** [comment]
What happened with the toolboxd approach?  It sounds like it should work.

**Comment by debarshiray** [comment]
> What happened with the toolboxd approach? It sounds like it should work.

It is a work in progress.

**Comment by debarshiray** [comment]
I am going to close this. There's no point in having a catch-all *make toolboxd work* issue. It's just too open-ended.
