### ISSUE TITLE
Bashisms with /bin/sh shebang 

### ISSUE THREAD

**Issue by aimileus** [debarshiray/toolbox#53]
Currently fedora-toolbox has `/bin/sh` as shebang, implying that only POSIX shell functions are used. For example in Debian/Ubuntu based distributions, `/bin/sh` is not a symlink to bash, but to dash, which does not support bash extensions (see https://wiki.debian.org/DashAsBinSh). However, fedora-toolbox uses a couple of these bash functions. I ran the checkbashisms script to check for this, and it contained a couple of bash-exclusive features as of 4cf58d5b729571152a6255404b9af4cc81dcac58 (see https://gist.github.com/aimileus/e83db1f70344846d98f4e1aff071644b).

**Comment by debarshiray** [comment]
I replace `source` with `.` in commit b3a6578cc955585ad9b3d9bf85cc81778e00a439. The rest need a closer look.

**Comment by debarshiray** [comment]
I don't understand this issue:
```
possible bashism in toolbox line 21 (should be >word 2>&1):
base_toolbox_command=$(basename "$0" 2>&42)
```

What's `word` supposed to be?

Either way, thanks for stopping by.

**Comment by aimileus** [comment]
Thanks for responding! According to the Ubuntu wiki, dash only supports single digit file descriptors (https://wiki.ubuntu.com/DashAsBinSh#flock).  I *think* "word" is just the base command (in this case basename "$0"). I did not check the entire script thoroughly, but I only the digit of the file descriptor (42) should need to change.

**Comment by tosmi** [comment]
@debarshiray: if this was the file descriptor, this ticket could probably be closed...

**Comment by aimileus** [comment]
@tosmi Yes, that was part of this ticket. However, there are two more issues left, see #56 for the remaining bashisms.

**Comment by tosmi** [comment]
oh, my fault, sorry.

**Comment by debarshiray** [comment]
@tosmi Just one issue left now in #56 about what `echo -e` is supposed to do.

**Comment by debarshiray** [comment]
Everything in #56 got merged. Closing.
