### ISSUE TITLE
onboarding friendliness

### ISSUE THREAD

**Issue by matthiasclasen** [debarshiray/toolbox#59]
I did a fresh install of silverblue. fedora-toolbox was installed. But I didn't quite know how to get started, so I just ran it:

```
$ fedora-toolbox
/usr/bin/fedora-toolbox: missing command
Try '/usr/bin/fedora-toolbox --help' for more information.
```

Thats not terrible, but it could be nicer. 
- Don't show the full path. 'fedora-toolbox' is enough
- Give me some hints how to get started, Something like "Use the 'create' command to create a toolbox", would be helpful
- For a minute, I was confused and thought there was some installation issue where fedora-toolbox was missing some tool it relies on. The error message could be clearer.
- Not so much a newcomer thing, but completion would be great to explore available commands

After this, I tried: man fedora-toolbox - and was greeted by another error message.
Its a commandline tool, it should have a man page.

Eventually, I figured I need to run: fedora-toolbox create. It did something! It did not really give me any for what to do next, but I just tried: fedora-toolbox enter. Sadly, this gives

```
$ fedora-toolbox enter
/usr/bin/fedora-toolbox: failed to start container fedora-toolbox-mclasen:30
```

At this point, I'm stuck. What is wrong? What to do next?

**Comment by juhp** [comment]
I tend to agree I don't really like this trend of `use --help` to get help... just give me the help already. :-)

**Comment by debarshiray** [comment]
> I don't really like this trend of use --help to get help... just give me the
> help already. :-)

Yeah, I'd like to make the command line parsing and associated error messages a bit more fault tolerant but the shell offers very limited facilities. Hopefully things will be better once we rewrite in Go. :)

**Comment by matthiasclasen** [comment]
We changed flatpak to use this style of error message since it can be a bit overwhelming to get confronted with a screenful of --help output for a simple typo.

**Comment by debarshiray** [comment]
> We changed flatpak to use this style of error message since it can be a bit
> overwhelming to get confronted with a screenful of --help output for a simple
> typo.

Ok, good to know.

For the time being, I am trying to make the `toolbox` error messages context-sensitive so that it suggests what the obvious solution might be, with a hint as to how to get more detailed documentation. For example:
```
$ toolbox 
toolbox: missing command

These are some common commands:
create    Create a new toolbox container
enter     Enter an existing toolbox container
list      List all existing toolbox containers and images

Try 'toolbox --help' for more information.
$ toolbox enter
toolbox: container fedora-toolbox-rishi-29 not found
Use the 'create' command to create a toolbox.
Try 'toolbox --help' for more information.
$ toolbox create
Created container: fedora-toolbox-rishi-29
Enter with: toolbox enter
```

**Comment by debarshiray** [comment]
@fmuellner added Bash completion in PR #133

**Comment by debarshiray** [comment]
Closing.
