### ISSUE TITLE
Failed to create containers unless attaching portable devices

### ISSUE THREAD

**Issue by memnoth** [debarshiray/toolbox#80]
Without attaching portable devices such as USB and so on, creating containers is on failure while ``toolbox create``.
```
error checking path "/run/media": stat /run/media: no such file or directory
toolbox: failed to create container fedora-toolbox-thomas:29
```

**Comment by debarshiray** [comment]
Yes, this is because of https://github.com/debarshiray/toolbox/commit/0c848abd1893764f2e0bb62334972d67f95dafd1

I'd suggest installing the toolbox-0.0.7 RPM, followed by a `systemd-tmpfiles --create`.

**Comment by debarshiray** [comment]
Also, this doesn't matter on Silverblue, which is the most critical target environment for the toolbox, where `rpm-ostree` ensures that `/run/media` is created during boot.

Closing.
