### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by jimmac** [debarshiray/toolbox#81]
Apparently no project is taken seriously before it has a logo. Let's figure that one out.

**Comment by jimmac** [comment]
Here's a couple of initial sketches / ideas:

**Wrench**
- uses the same outline as the Silberblue logo
![Fedora_Toolbox](https://user-images.githubusercontent.com/14821/54553868-6f7dcd80-49b3-11e9-83a0-d04ee9ef1883.png)

**Hex silhouette**
- use the hex shape to double as a hip sticker
![Fedora_Toolbox 2](https://user-images.githubusercontent.com/14821/54553961-a358f300-49b3-11e9-9909-49dbea11828d.png)

**Terminal**
- Fedora Toolbox is about making CLI great again
![Fedora_Toolbox 3](https://user-images.githubusercontent.com/14821/54554058-d1d6ce00-49b3-11e9-8852-079584a06dcb.png)

**Comment by debarshiray** [comment]
I love them all, but I have a slight preference for the hex silhouette.

**Comment by jimmac** [comment]
Few attempts at combining the wrench and the commandline have made me rethink the extruded 3d shape. A flat 2D shape is probably way more clear and inline with what Silverblue is using.

![Fedora_Toolbox 5](https://user-images.githubusercontent.com/14821/54585650-f6b25c00-4a1a-11e9-9887-75fb45e613a1.png)
![Fedora_Toolbox 4](https://user-images.githubusercontent.com/14821/54585653-f87c1f80-4a1a-11e9-84b9-9b1c434856de.png)

These are too complex for their own good.

**Comment by jimmac** [comment]
Another approach -- using the Silverblue silhouette, a dot grid with a prompt.

![Fedora_Toolbox 6](https://user-images.githubusercontent.com/14821/54587489-7f7fc680-4a20-11e9-9a42-e9ef37bedc88.png)

**Comment by debarshiray** [comment]
Thanks a lot for working on these, @jimmac !

Note that we dropped the `fedora` prefix from the project name and it's now just `toolbox`, but I don't mind having a subtle tip of the hat to recognize Fedora's pioneering role in this area.

**Comment by jimmac** [comment]
Not particularly keen on this one, but it is a tangent that's perhaps worth sharing. 

![IMG_0277](https://user-images.githubusercontent.com/14821/54591246-261c9500-4a2a-11e9-908a-4de19acd1e0d.PNG)

![IMG_0278](https://user-images.githubusercontent.com/14821/54591254-2b79df80-4a2a-11e9-85ab-1e0f065af0a6.GIF)



So far I we're still at the exploratory stage, no clear direction apart from:
- No strong Fedora link
- CLI, overlay, tool, computer savvy
- Silverblue relatated a plus

**Comment by jimmac** [comment]
Some more explorations with a stronger link to the Silverblue logo.

![Fedora_Toolbox 8](https://user-images.githubusercontent.com/14821/54687454-e33aea00-4b1b-11e9-8086-8f373cc5692b.png)
![Fedora_Toolbox 9](https://user-images.githubusercontent.com/14821/54687455-e3d38080-4b1b-11e9-8f01-01b5f662d385.png)

**Comment by matthiasclasen** [comment]
I don't think we want a too strong association with silverblue here - the toolbox is going to be shared with coreos

**Comment by jimmac** [comment]
![toolbox-logo](https://user-images.githubusercontent.com/14821/54940929-0276b480-4f2c-11e9-9540-9987a5a2b50c.png)

**Comment by matthiasclasen** [comment]
very hexstickerable! :)

**Comment by debarshiray** [comment]
Yes, I love this purple wrench in a purple hexagon!

**Comment by debarshiray** [comment]
@jimmac are we at a stage where we can settle around the "purple wrench in a purple hexagon" idea?

**Comment by jimmac** [comment]
A little straight forward, but if you're happy, I'm happy.

**Comment by debarshiray** [comment]
Yes, I am happy! :)

Are you planning to create some variants? eg., a more [horizontally stretched out](https://raw.githubusercontent.com/containers/libpod/master/logo/podman-logo-source.svg?sanitize=true) image would fit better in `README.md`.

**Comment by jimmac** [comment]
Initial stab at some guidelines:

[toolbox-logo-specimen.pdf](https://github.com/debarshiray/toolbox/files/3022683/toolbox-logo-specimen.pdf)

**Comment by debarshiray** [comment]
We now have various variants of the  "white wrench in a purple hexagon" and guidelines for using them in `master`. Closing.
