### ISSUE TITLE
Add ttyUSB dialup devices in the toolbox

### ISSUE THREAD

**Issue by mildred** [debarshiray/toolbox#97]
Sometimes, in the toolbox, you need to access external hardware, either to communicate with an external device or flash a chip. Inside the toolbox, `/dev/ttyUSB*` is empty.
It would be nice if those devices were available. Possibly those devices can only appear after the toolbox has been entered. Perhaps sharing the entire `/dev` tree would not be that bad.

**Comment by debarshiray** [comment]
I don't have any `/dev/ttyUSB*` on my host currently. I suppose those are just files under `/dev`, and not sub-directories, right?

I think we should look at bind mounting the entire `/dev`. @rhatdan warned me that PTYs could cause problems, and I haven't looked into that.

**Comment by mildred** [comment]
> I don't have any /dev/ttyUSB* on my host currently. I suppose those are just files under /dev, and not sub-directories, right?

Yes, directly under `/dev`, and they appear dynamically (when you plug an USB serial device). I was convinced for no good reason that it was impossible to share /dev inside the toolbox, but if you do this at the toolbox creation, it works

**Comment by mildred** [comment]
With PR #119, if I manually chown the device to my user/group on the host, I can access it from within the toolbox.

However, if I make myself part of the dialup group (the ttyUSB0 device is owned by root:dialup), the device appears as nobody:nobody in the toolbox and is inaccessible although it's accessible on the host.

**Comment by thawkins** [comment]
You should also support /dev/ttyACMx style devices too, they are often used for arduino, cnc, laser engraver and 3d Printer connections.

**Comment by debarshiray** [comment]
Now that PR #119 has been merged, this issue can be closed.

> You should also support /dev/ttyACMx style devices too, they are often
> used for arduino, cnc, laser engraver and 3d Printer connections.

New toolbox containers will have the entire `/dev` bind mounted from the host. So barring permission problems arising out of the files not being world accessible, things should be working now.
